insolar/block-explorer

.codecov.yml
.editorconfig
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/mergeable.yml
.github/workflows/tests.yaml
.pre-commit-config.yaml
Makefile
go.mod

Add a GitHub workflow and Makefile

Penv-207: GitHub actions

---

LICENSE.md

Update link to License file in License file

PENV-192: update license

---

etl/types.go

PENV-208: add common types

---

etl/interfaces.go

Add interfaces for Processor and Controller
Check interfaces at docs

PENV-209: components interfaces

---

etl/interfaces.go
etl/models/models.go

Penv 263 db models

---

etl/types/types.go

PENV-279: Clean metrics after insolar was imported

PENV-279: Clean metrics after insolar was imported

---

.dockerignore
Dockerfile
Makefile
cmd/block-explorer/main.go
docker-compose.yaml
etl/extractor/mainnet_impl.go
etl/processor/processor.go
etl/transformer/transformer.go

I have joined all components together 
Add docker-compose support
Dates able to fill in the DB

Penv-281: join all components

---

cmd/block-explorer/main.go
etl/processor/processor.go
etl/processor/processor_test.go
etl/types/types.go
go.mod
test/integration/db_integration_test.go
testutils/canonical.go
testutils/generators.go

Process jetDrop and send information about saved data to controller
Add tests
Run tests

Penv 213 process jetdrop

---

etl/dbconn/connection.go
etl/storage/storage.go
etl/storage/storage_test.go
testutils/db.go
testutils/models.go

PENV-267: save jet drop to db

---

etl/interfaces/interfaces.go
etl/interfaces/mock/storage_mock.go
etl/interfaces/mock/storage_setter_mock.go
etl/storage/storage.go
etl/storage/storage_test.go

Add to storage methods for saving pulse and update it to complete
Add tests
Run tests

Penv 266 save and complete pulse at db

---

test/heavymock/exporter_impl.go
test/heavymock/import_records_impl.go
test/heavymock/import_records_test.go
test/integration/db_integration_test.go
test/integration/importer_test.go

Clean heavymock after sending records to BE
run tests

PENV-342 clean heavymock after sending records

---

cmd/block-explorer/main.go
cmd/migrate/migrate.go
configuration/configuration.go
etl/connection/grpc_client.go
etl/connection/grpc_client_component_test.go
etl/connection/grpc_client_test.go
etl/extractor/platform_impl.go
etl/extractor/platform_integration_test.go
etl/types/types.go
instrumentation/belogger/logger.go
test/heavymock/heavymock_test.go
test/heavymock/import_records_test.go
testutils/connectionmanager/connectionmanager.go

resolved log todos
removed prints
renaming

PENV-297 logs and renaming

---

testutils/grpc.go

PENV-345 fix linter

---

etl/transformer/error.go
etl/transformer/transformer.go
etl/transformer/transformer_test.go
testutils/generators.go

skip records which not supported yet 
with new error in transformer layer 

PENV-261: skip unsupported record

---

cmd/block-explorer/main.go
configuration/configuration.go
etl/controller/controller.go
etl/controller/controller_test.go
etl/controller/pulsemaintainer.go
etl/controller/pulsemaintainer_test.go
go.mod
go.sum
testutils/betestsetup/betestsetup.go

special goroutine in controller for checking pulse completness

PENV-217: Pulse completion checker cycle

---

.github/workflows/tests.yaml
Makefile
test/integration/db_integration_test.go
test/integration/receive_records_test.go

- Send results of the mock integration tests to TestRail on scheduled runs and on push to master
- Link existing integration tests to test cases in TestRail
- remove obsolete tests
will be active after this branch is pushed to master 

PENV-293 send test run results to testrail

---

Makefile
Makefile.build
Makefile.testing

Split the Makefile into two parts

PENV-349: split makefile

---

api/handlers.go
api/handlers_test.go
api/mappers.go
etl/interfaces/interfaces.go
etl/interfaces/mock/storage_mock.go
etl/storage/storage.go
etl/storage/storage_test.go

Add handler for `/api/v1/pulses/:pulse_number` url
Add tests for it
Run tests

Penv 256 api pulse by number

---

api/handlers.go
api/handlers_test.go
etl/interfaces/interfaces.go
etl/interfaces/mock/storage_mock.go
etl/storage/storage.go
etl/storage/storage_test.go

added search by jet id, without ancestors/descendants

PENV-257 search jet by jet id

---

api/mappers.go

check prototype before converting to str
add test values to jetDrop links

NOISSUE: check prototype before converting to str

---

api/handlers.go
api/handlers_test.go
api/mappers.go
etl/models/models.go

fixed bug with nil value on total=0
in lifeline
in jetdrops
in records

NOISSUE fixing nil bugs

---

api/handlers.go
api/handlers_test.go
testutils/models.go

PENV-262: search handler

---

api/handlers_test.go
api/mappers.go
docker-compose.yaml
etl/controller/controller.go
etl/controller/controller_test.go
etl/controller/pulsemaintainer.go
etl/interfaces/interfaces.go
etl/interfaces/mock/controller_mock.go
etl/models/models.go
etl/processor/processor_test.go
etl/storage/storage_test.go
etl/transformer/mainnet_test.go
etl/transformer/transformer.go
etl/types/types.go
instrumentation/converter/platform.go
migrations/migrations.go
test/integration/db_integration_test.go
testutils/canonical.go
testutils/models.go

changed JetID from []byte to string 
with tests and with the real heavy looking in DB 

PENV-259: change jetid from []byte to string

---

migrations/migrations.go

return initial table for migration 
add table name in indexes 

Penv-259: return initial table for migration

---

.github/workflows/build.yaml
Dockerfile

add workflow for building docker image and pushing it to public registry

OPS-283: docker build&push workflow

---

api/handlers.go
configuration/configuration.go
etl/controller/controller.go
etl/controller/controller_test.go
etl/controller/misseddata.go
etl/controller/pulsemaintainer.go
etl/controller/pulsemaintainer_test.go
etl/interfaces/interfaces.go
etl/interfaces/mock/storage_mock.go
etl/interfaces/mock/storage_setter_mock.go
etl/models/models.go
etl/processor/processor.go
etl/storage/storage.go
etl/storage/storage_test.go
migrations/migrations.go
testutils/betestsetup/betestsetup.go

- add to pulse property `IsSequential`: it means all data from min pulse to this pulse included were successfully saved to db
- Controller checks pulses and set `IsSequential` property
- Controller call Extractor for loading missing data
Run tests

Penv 218 reload missing data controller

---

api/handlers.go
api/handlers_test.go
etl/interfaces/interfaces.go
etl/storage/storage.go
etl/storage/storage_test.go

delete hardcoded sort value
use sort value from the generated server 
passing the boolean value into the function 
with tests and frontend 

PENV-401: delete hardcoded sort_by index parameter 

---

cmd/block-explorer/main.go
etl/extractor/platform_impl.go
etl/extractor/platform_pulse.go
etl/processor/processor.go
etl/transformer/mainnet_impl.go
etl/transformer/transformer.go

PENV-403: make log a bit shorter

---

.github/workflows/build.yaml

Build master branch on every push and push image to public registry with tag :latest

NOISSUE: build master as :latest

---

etl/storage/storage_test.go
testutils/models.go

fix the flaky test. 
decrease test execution time by bulk insert 
add regexp prefix for finding all possible jet splits 

Penv-409: fix test

---

Makefile.testing
api/handlers.go
api/handlers_test.go
go.mod
go.sum

Update spec to `v1.1.1` with increased `limit` to 1000
run tests

PENV-410: set limit to 1000

---

test/api/apiwrapper.go
test/api/helpers.go
test/api/pulses_test.go

implement integration tests for endpoint pulses/
run tests

PENV-381: api pulses tests

---

etl/controller/misseddata.go

check the array length before getting access 

PENV-412: fix deleteExpired function

---

etl/storage/storage.go
test/api/apiwrapper.go
test/api/pulse_test.go

Integration tests for endpoint `pulses/{pulse_number}`

PENV-382: api get pulse 

---

api/mappers.go
go.mod
go.sum

add new spec version for prev and next jetdrop data

PENV-346: new spec version for prev and next jetdrop data

---

api/handlers_test.go
etl/models/models.go
test/api/apiwrapper.go
test/api/jd_by_id_test.go
test/api/jd_by_pulse_test.go

tests for  endpoint `/jet-drops/{jet-id}`
also fixed small issue with url encoding

PENV-380: api tests for endpoint GetJetDropsByID

---

test/api/apiwrapper.go
test/api/helpers.go
test/api/jd_by_id_test.go
test/api/search_test.go

PENV-385 tests for endpoint /search

---

etl/transformer/transformer.go

…cord
delete getting prototypeReference for virtual deactivate record because this record does not have an Image

PENV-368: delete getting prototypeReference for virtual deactivate record

---

etl/models/models.go

change pk order. it won't have behaviours in application logic. 
It needs to make update insert 

PENV-447: change pk order because of GORM internal problem

---

docker-compose.yaml

PENV-396: docker-compose refactoring

---

cmd/migrate/migrate.go
migrations/migrations.go
testutils/db.go

execute migrations inside a single transaction
cause migrate to fail if there's unknown migration 

PENV-415: do migration in one transaction

---

api/handlers_test.go
test/api/pulse_test.go

PENV-414: pulse_number cannot be greater than int64

---

configuration/configuration.go
etl/connection/credentials.go
etl/connection/credentials_test.go
etl/connection/grpc_client.go
etl/connection/grpc_client_test.go

Add ability connect to heavy with authorisation  
tests and testnet 

Penv-453: heavy authorization  

---

configuration/configuration.go
docker-compose.yaml

increase the ReloadPeriod value because of DB is slow

PENV-447: fix some data reloading

---

etl/transformer/transformer.go

- Set objectReference for result record
- Set objectReference for incomingRequest records, created at Genesis
Run BE and platform, all records have object ref

PENV-400: set object ref to req and res

---

api/pprof_router.go
cmd/block-explorer/main.go

add pprof router to block-explorer app 

PENV-389: add pprof

---

etl/controller/pulsemaintainer.go

block the map field when rage and delete. No slowdowns found

PENV-464: fix race detection on jetDropRegister

---

cmd/block-explorer/main.go
configuration/configuration.go
docker-compose.yaml

increase processor worker count by config 
describe config for a processor and take value from there 

PENV-389: increase processor worker count by config

---

cmd/api/main.go
configuration/configuration.go

PENV-389: connection timeout for api

---

etl/controller/pulsemaintainer.go
etl/controller/pulsemaintainer_test.go
go.sum

added complete pulse check algorithm for platform 1.x
tests

PENV-216 added complete pulse check algorithm

---

test/api/apiwrapper.go
test/api/jd_by_id_test.go
test/api/jd_by_jetid_test.go
testutils/generators.go

integration tests for endpoint /jets/{jet-id}/jetdrops

PENV-386 api tests get JetDrops by JetID

---

.github/workflows/tests.yaml
Makefile.testing
etl/connection/credentials_test.go
test/api/apiwrapper.go
test/api/jd_records_test.go
testutils/generators.go

api integration tests for endpoint `/jetdrops/{jetdrop-id}/records`
fixed issue when tests failed on ci but job result was success
partly covered test case with star as part of jetDropID

PENV-384 api tests records by JetDropID

---

test/api/jd_by_jetid_test.go

NOISSUE rename duplicated test name

---

etl/controller/controller.go
etl/controller/controller_test.go
etl/controller/pulsemaintainer.go
etl/controller/pulsemaintainer_test.go

Change jetDropRegister from list to map (to make it uniq and more easy to check fullness)
Run tests

NOISSUE: make jetDropRegister map

---

.github/workflows/tests.yaml
Makefile.testing

Remove duplicated `-timeout` param when running tests

NOISSUE fix nightly test run

---

etl/storage/storage.go
etl/storage/storage_test.go

Save pulses to db under lock to avoid "duplicate key" error 
Add test to check saving of same pulse several times in parallel
Run tests

PENV-479: save pulse under lock

---

api/handlers.go
api/handlers_test.go
api/mappers.go
etl/interfaces/interfaces.go
etl/interfaces/mock/storage_mock.go
etl/interfaces/mock/storage_setter_mock.go
etl/models/models.go
etl/processor/processor.go
etl/processor/processor_test.go
etl/storage/storage.go
etl/storage/storage_bench_test.go
etl/storage/storage_test.go
migrations/migrations.go
testutils/generators.go

save jetdrop and record amount inside pulse to prevent CPU overloading
extended pulse DTO

Penv-481: save jetdrop and record amount

---

docker-compose.yaml
etl/extractor/extractor_bench_test.go
etl/extractor/helpers_test.go
etl/extractor/platform_test.go
test/integration/db_integration_test.go
testutils/generators.go
testutils/generators_test.go

Penv 347 fix benchmark

---

etl/dbconn/connection_test.go

PENV-493: TestShutDownPlugin fix data race

---

test/integration/helper.go
test/integration/integration_bench_test.go

Tests within Bench-integration now send records properly to be processed by pulse retriever.
Bench successfully ends on this branch locally. Meanwhile CI on this PR will be failed as expected. 
Should be fixed after merging to master

PENV-498 fix bench integration

---

test/integration/helper.go

Remove sleep, logic was change at PENV-347

PENV-343: remove sleep in tests

---

api/handlers.go

temporary change the limit for storage blockchain 

PENV-505: change the jetdrops limits temporary

---

etl/transformer/transformer.go
instrumentation/converter/platform.go
testutils/clients/pulse_client.go

change PulseTimestamp from nanosecond to second 
in the frontend

PENV-402: change PulseTimestamp from nanosecond to second

---

etl/dbconn/connection_test.go

the main problem was when we registred the plugins. each registration added to the end of the callbacks for calling consistently. sometimes we had received the channel before calling the last callback plugin. that's why we got an error. 
now plugin order was changed. 

PENV-500: fix flaky test TestShutDownPlugin

---

etl/extractor/platform_impl.go
etl/transformer/transformer_test.go
test/integration/db_integration_test.go

Add unit test and integration test to check BE behavior if same records was provided via exporter several times.
Run tests

PENV-418: same records test

---

go.mod
go.sum

update insolar version as in  mainnet 

PENV-402: update insolar version

---

.github/workflows/tests.yaml
etl/storage/storage_test.go
test/api/jd_by_pulse_test.go

Penv 511 correct check record in db at test

---

cmd/api/main.go
cmd/block-explorer/main.go
go.mod

NOISSUE: add profiler

---

api/handlers.go
api/handlers_test.go
api/mappers.go
etl/storage/storage.go
etl/storage/storage_test.go
test/api/pulse_test.go
test/api/pulses_test.go

If prev or next pulses for current pulse not exist in db, we dont return it to api
Run tests

PENV-521: no prev next pulse if not in db

---

cmd/api/main.go
go.mod
go.sum
scripts/monitor/docker-compose.yml
scripts/monitor/grafana/config.ini
scripts/monitor/grafana/dashboards/api.json
scripts/monitor/grafana/provisioning/dashboards/all.yaml
scripts/monitor/grafana/provisioning/datasources/all.yaml
scripts/monitor/prometheus/prometheus.yaml

Added metrics for API
Added the docker-compose for setup the dashboard locally 

Penv-220: api metrics

---

etl/extractor/platform_impl.go

fix error message check and added some debug

penv-527 fix error message and some debug

---

scripts/monitor/grafana/dashboards/storage.json

PENV-221: fix storage dashboard

---

etl/extractor/platform_impl.go

trying to close stream using context 

PENV-520: close stream via context

---

test/api/jd_by_id_test.go

apitest get JetDrop by JetDropID = * (get genesis records) 

PENV-462 apitest get JetDrop by JetDropID = *

---

.gitignore
cmd/block-explorer/main.go
etl/controller/controller.go
etl/controller/metrics.go
etl/controller/pulsemaintainer.go
etl/extractor/metrics.go
etl/extractor/platform_impl.go
etl/interfaces/interfaces.go
etl/interfaces/mock/jet_drops_extractor_mock.go
etl/storage/db_stats_metrics.go
etl/storage/postgres_metrics.go
etl/storage/storage_metrics.go
etl/transformer/mainnet_impl.go
etl/transformer/mainnet_test.go
etl/transformer/metrics.go
etl/transformer/transformer.go
etl/types/types.go
instrumentation/metrics/prometheus.go
scripts/monitor/grafana/dashboards/main.json
test/integration/db_integration_test.go

Penv 538 metrics

---

.github/workflows/tag_processing.yml

add workflow for processing tags

OPS-325: add workflow for processing tags

---

api/handlers.go
api/handlers_test.go
etl/interfaces/interfaces.go
etl/storage/storage.go
etl/storage/storage_test.go
go.mod
go.sum

add new filtering for /pulses endpoint
update spec's 
with tests 

Penv-548: pulses filters

---

etl/controller/metrics.go

PENV-580: fix metrics duplication

---

api/handlers.go

no need to log RecordNotFoundError or nil error. 

NOISSUE: do not log RecordNotFoundError or nil error

---

test/api/apiwrapper.go

make be api client public in order to be usable in other projects

NOISSUE importable apiclient

---

scripts/monitor/grafana/dashboards/api.json
scripts/monitor/grafana/dashboards/main.json
scripts/monitor/grafana/dashboards/storage.json
scripts/monitor/grafana/provisioning/datasources/all.yaml

fix metrics rate and datasource 

NOISSUE: fix metrics

---

api/handlers.go
api/handlers_test.go
etl/interfaces/interfaces.go
test/api/jd_by_jetid_test.go
testutils/generators.go
testutils/generators_test.go

fixed bug when prev/next jetdrop wasn't set on jetid siblings on edge pulses

Penv 555 jetdrops bug

---

etl/storage/db_stats_metrics.go
etl/storage/postgres_metrics.go
etl/storage/storage.go
etl/storage/storage_metrics.go
instrumentation/metrics/prometheus.go
scripts/monitor/grafana/dashboards/storage.json

fix and extend metrics dashboard
fix refresher for metrics 

NOISSUE: fix metrics dashboard and add new one

---

Makefile.build

Add new target in Makefile which allows to compile test files 

PENV-335 compile tests in Makefile

---

go.mod
go.sum
test/api/apiwrapper.go
test/api/jd_records_test.go

With block-explorer spec updated to master, fix compilation errors in tests

PENV-335 fix tests compilation with latest spec

---

etl/controller/controller.go
etl/controller/metrics.go
etl/controller/pulsemaintainer.go
etl/extractor/metrics.go
etl/extractor/platform_impl.go

penv-601 added metrics

---

etl/controller/controller.go
etl/controller/metrics.go
etl/controller/pulsemaintainer.go
etl/extractor/metrics.go
etl/extractor/platform_impl.go

Penv 601 workers fix

---

cmd/api/main.go
cmd/block-explorer/main.go
configuration/configuration.go
go.mod
go.sum
instrumentation/profefe/profefe.go

add integration with [profefe](https://github.com/profefe/profefe)  collector 

Penv-602: add profefe

---

test/api/jd_by_jetid_test.go

generate properly unique jetID to get empty api result

NOISSUE fix flaky test TestGetJetDropsByJetID

---

cmd/block-explorer/main.go
etl/extractor/extractor_bench_test.go
etl/extractor/platform_impl.go

fix problem of stop saving pulse data on heavy overtake

penv-624 fix heavy overtake

---

test/api/jd_by_jetid_test.go

TestGetJetDropsByJetID failed on nightly
go test -v ./test/api/... -run TestGetJetDropsByJetID -count=1000 -tags heavy_mock_integration

NOISSUE once again fix flaky nightly test

---

etl/storage/storage.go
scripts/monitor/grafana/dashboards/main.json

removed lock, updated dashboard

Penv 614 storage research

---

etl/storage/storage_metrics.go
scripts/monitor/grafana/dashboards/storage.json

penv-614 dashboard

---

etl/extractor/platform_impl.go

freeing worker fix, 
added 3 worker scheme

penv-615 freeing worker fix, added 3 worker scheme

---

api/handlers.go
api/handlers_test.go

Correct  timestampLte api param processing
Add api test to check this param
Run tests

PENV-652: correct timestamp api param

---

api/handlers.go
cmd/block-explorer/main.go
configuration/configuration.go
etl/controller/controller.go
etl/controller/controller_test.go
etl/controller/metrics.go
etl/controller/misseddata.go
etl/controller/pulsemaintainer.go
etl/controller/pulsemaintainer_test.go
etl/extractor/extractor_bench_test.go
etl/extractor/platform_impl.go
etl/extractor/platform_test.go
etl/interfaces/interfaces.go
etl/interfaces/mock/storage_mock.go
etl/processor/processor.go
etl/storage/storage.go
etl/storage/storage_test.go
etl/transformer/mainnet_impl.go
etl/transformer/mainnet_test.go
go.mod
instrumentation/belogger/log_cfg_test.go
testutils/betestsetup/betestsetup.go

penv-614 priority poc

---

.github/workflows/gbe-system-tests.yaml
deploy/autotests/kustomization.yaml
deploy/block-explorer/block-explorer-patch.yaml
deploy/block-explorer/external-svc.yaml
deploy/block-explorer/kustomization.yaml

new workflow `system-tests / test (gbe-system-tests)` runs on pull requests
see [workflow run ](https://github.com/insolar/block-explorer/pull/188/checks?check_run_id=1188100443)

PENV-630 run gbe-system-tests on pull requests

---

etl/controller/controller_test.go

fix the leak test by stopping the controller 

PENV-672: fix leak test

---

api/handlers_test.go
docker-compose.yaml
etl/models/models.go
etl/storage/storage.go
etl/storage/storage_test.go
migrations/migrations.go
testutils/models.go

add  table request and state in migration scripts and create new models
starting migrate `make migrate`

PENV-787,PENV-788: create new table request and state and index

---

api/handlers.go
api/handlers_test.go
api/mappers.go
go.mod
go.sum
test/api/apiwrapper.go
test/api/jd_records_test.go

update spec in go.mod to latest
refactor some tests due to broken backward compatibility
run tests

PENV-773 bump spec version

---

.github/workflows/build.yaml

build and push images on release branch

NOISSUE: build images in release branch

---

deploy/autotests/kustomization.yaml

NOISSUE update go autotests image

---

etl/processor/processor.go
etl/processor/processor_test.go
etl/transformer/mainnet_test.go
etl/transformer/transformer.go
etl/transformer/transformer_bench_test.go
etl/transformer/transformer_test.go
etl/types/types.go
test/integration/db_integration_test.go
testutils/canonical.go

Was created a new type of record - **State**
Updated transformer and processing layers.
Temporary operate with `IRecord` interface.
Running the tests
**- Clarification**
Storage will be done in another task.

PENV-785: process state types switch to IRecord interface

---

etl/interfaces/interfaces.go
etl/interfaces/mock/storage_mock.go
etl/interfaces/mock/storage_setter_mock.go
etl/models/models.go
etl/processor/processor.go
etl/processor/processor_test.go
etl/storage/storage.go
etl/storage/storage_bench_test.go
etl/storage/storage_test.go
go.mod
go.sum
test/api/pulse_test.go
test/api/pulses_test.go
test/integration/db_integration_test.go
testutils/generators.go
testutils/models.go

Save the state object to the states table.
Switched to `models.IRecord` interface temporarily.
Running the tests

PENV-786: Storage State

---

.github/workflows/tests.yaml

run tests on release branch in addition to master branch

OPS-385 trigger tests on push to release branch

---

etl/exporter/pulse_exporter_server_integration_test.go
etl/storage/storage.go
etl/storage/storage_test.go

add new pulse exporter integration tests**
- How I did it**
with test postgres 

PENV-768: add pulse exporter integration tests

---

cmd/exporter-api/main.go
etl/exporter/metrics.go
instrumentation/metrics/prometheus.go
scripts/monitor/grafana/dashboards/exporter-grpc-api.json

penv-807 grpc metrics

---

etl/models/models.go
etl/processor/processor.go
etl/storage/storage.go
etl/storage/storage_test.go
migrations/migrations.go
testutils/models.go

Save request to the requests table
Running the tests

PENV-794: request storage

---

api/handlers.go
api/handlers_test.go
api/mappers.go
etl/interfaces/interfaces.go
etl/storage/storage.go
etl/storage/storage_metrics.go
migrations/migrations.go
testutils/models.go

PENV-795: get request

---

test/api/apiwrapper.go
test/api/state_test.go
testutils/generators.go

PENV-773 get state api tests

---

.github/workflows/gbe-system-tests.yaml
.github/workflows/tests.yaml

NOISSUE disable scheduled jobs
